-- MySQL Script generated by MySQL Workbench
-- Sun Oct 16 21:06:05 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `UserID` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(45) NOT NULL,
  `NickName` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Role` VARCHAR(45) NOT NULL,
  `Image` VARCHAR(45) NULL,
  `Gender` VARCHAR(45) NOT NULL,
  `Birthday` DATE NOT NULL,
  `Question` VARCHAR(45) NOT NULL,
  `Answer` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UserID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Notice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Notice` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Notice` (
  `NoticeID` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(45) NOT NULL,
  `Date` DATE NOT NULL,
  `Venue` VARCHAR(45) NOT NULL,
  `Contact` VARCHAR(45) NOT NULL,
  `Description` MEDIUMTEXT NULL,
  `Image` VARCHAR(45) NULL,
  `State` VARCHAR(45) NOT NULL,
  `User_UserID` INT NOT NULL,
  PRIMARY KEY (`NoticeID`, `User_UserID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Respond`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Respond` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Respond` (
  `RespondID` INT NOT NULL AUTO_INCREMENT,
  `Message` LONGTEXT NOT NULL,
  `Notice_NoticeID` INT NOT NULL,
  `User_UserID` INT NOT NULL,
  PRIMARY KEY (`RespondID`, `Notice_NoticeID`, `User_UserID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
